### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by ramkumarkoppu** [WesleyHsieh0806/TAO-Amodal#2]
couldn't find the code to use model and model files in the repo.

**Comment by WesleyHsieh0806** [comment]
will be released soon

**Comment by WesleyHsieh0806** [comment]
All the code has been released! @ramkumarkoppu 

We recommend checking our dataset first by using the [visualization scripts](https://github.com/WesleyHsieh0806/TAO-Amodal/blob/main/visualization/Readme.md)
