### ISSUE TITLE
Testing on video

### ISSUE THREAD

**Issue by Mohit-robo** [WesleyHsieh0806/TAO-Amodal#4]
Hey, great work on this. I wanted to test the performance of the detector and tracker on videos directly without using the dataset for evaluation purposes. Please can you guide me on this

**Comment by WesleyHsieh0806** [comment]
Please check the [demo](https://github.com/WesleyHsieh0806/Amodal-Expander/?tab=readme-ov-file#robot-demo) section.

Feel free to [customize the visualizer](https://github.com/WesleyHsieh0806/Amodal-Expander/blob/main/gtr/predictor.py) based on your purpose.
